var annotated_dup =
[
    [ "Accelerometer", "class_accelerometer.html", "class_accelerometer" ],
    [ "AHRS", "class_a_h_r_s.html", "class_a_h_r_s" ],
    [ "AHRS_complementary", "class_a_h_r_s__complementary.html", "class_a_h_r_s__complementary" ],
    [ "AHRS_EKF", "class_a_h_r_s___e_k_f.html", "class_a_h_r_s___e_k_f" ],
    [ "Barometer", "class_barometer.html", "class_barometer" ],
    [ "Control", "class_control.html", "class_control" ],
    [ "ControllerLoop", "class_controller_loop.html", "class_controller_loop" ],
    [ "ControllerLoopFACRO", "class_controller_loop_f_a_c_r_o.html", "class_controller_loop_f_a_c_r_o" ],
    [ "ControllerLoopFANGLE", "class_controller_loop_f_a_n_g_l_e.html", "class_controller_loop_f_a_n_g_l_e" ],
    [ "ControllerLoopFMANUAL", "class_controller_loop_f_m_a_n_u_a_l.html", "class_controller_loop_f_m_a_n_u_a_l" ],
    [ "ControllerLoopNONE", "class_controller_loop_n_o_n_e.html", "class_controller_loop_n_o_n_e" ],
    [ "ControllerLoopQACRO", "class_controller_loop_q_a_c_r_o.html", "class_controller_loop_q_a_c_r_o" ],
    [ "ControllerLoopQANGLE", "class_controller_loop_q_a_n_g_l_e.html", "class_controller_loop_q_a_n_g_l_e" ],
    [ "ControllerLoopQPOS", "class_controller_loop_q_p_o_s.html", "class_controller_loop_q_p_o_s" ],
    [ "ControllerLoopRANGLE", "class_controller_loop_r_a_n_g_l_e.html", "class_controller_loop_r_a_n_g_l_e" ],
    [ "ControllerLoopRAUTOLAUNCH", "class_controller_loop_r_a_u_t_o_l_a_u_n_c_h.html", "class_controller_loop_r_a_u_t_o_l_a_u_n_c_h" ],
    [ "ControllerLoopRGUIDED", "class_controller_loop_r_g_u_i_d_e_d.html", "class_controller_loop_r_g_u_i_d_e_d" ],
    [ "ControllerLoopRMANUAL", "class_controller_loop_r_m_a_n_u_a_l.html", "class_controller_loop_r_m_a_n_u_a_l" ],
    [ "ControlSystem", "class_control_system.html", "class_control_system" ],
    [ "EKF", "class_e_k_f.html", "class_e_k_f" ],
    [ "EKFParams", "struct_e_k_f_params.html", "struct_e_k_f_params" ],
    [ "Environment", "class_environment.html", "class_environment" ],
    [ "GPS", "class_g_p_s.html", "class_g_p_s" ],
    [ "GPSVel", "class_g_p_s_vel.html", "class_g_p_s_vel" ],
    [ "Gyroscope", "class_gyroscope.html", "class_gyroscope" ],
    [ "Magnetometer", "class_magnetometer.html", "class_magnetometer" ],
    [ "NS", "class_n_s.html", "class_n_s" ],
    [ "Params", "class_params.html", "class_params" ],
    [ "Sensor", "class_sensor.html", "class_sensor" ]
];